services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - 3005:3000
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - dashboard-app

  proxy:
      build: docker/proxy
      restart: always
      ports:
          - 3006:80
      depends_on:
          - grafana
      networks:
          - dashboard-app

networks:
  dashboard-app:
    driver: bridge
