services:
    db:
        image: mysql:8
        container_name: dashboard-db
        ports:
            - 13306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_NAME: mysql
        networks:
            - dashboard-app

    grafana:
        image: grafana/grafana
        container_name: grafana
        environment:
            - GF_SECURITY_ALLOW_EMBEDDING=true
        ports:
            - 3005:3000
        volumes:
            - ./docker/grafana/provisioning:/etc/grafana/provisioning
            - ./grafana-config:/usr/share/grafana/conf
        networks:
            - dashboard-app
        extra_hosts:
            - "host.docker.internal:host-gateway"

    proxy:
        container_name: proxy
        build: docker/proxy
        restart: always
        ports:
            - 0.0.0.0:3006:80
        depends_on:
            - grafana
        networks:
            - dashboard-app

    frontend:
        container_name: frontend
        build: ../vehikl-growth-session-dashboard
        ports:
            - 3000:3000
        stdin_open: true
        tty: true
        volumes:
            - ../vehikl-growth-session-dashboard:/app
        networks:
            - dashboard-app

    backend:
        container_name: backend
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        ports:
            - 8001:8001
        volumes:
            - .:/usr/src/app
            - ./public:/usr/src/app/public
        depends_on:
            - db
        networks:
            - dashboard-app
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    dashboard-app:
        driver: bridge
